name: Build and Push Docker Image
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image
        run: |
          docker build . --tag ghcr.io/unluckymichell/hz-web-next:latest --tag ghcr.io/unluckymichell/hz-web-next:${{steps.package-version.outputs.current-version}}
          docker push ghcr.io/unluckymichell/hz-web-next:latest
          docker push ghcr.io/unluckymichell/hz-web-next:${{steps.package-version.outputs.current-version}}
